# Generated by Django 2.1.5 on 2019-02-14 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availableday',
            name='supervisor',
        ),
        migrations.DeleteModel(
            name='AvailableDay',
        ),
    ]
