# Generated by Django 2.1.5 on 2019-03-05 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='abstract',
        ),
    ]
