# Generated by Django 2.1.5 on 2019-02-14 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190214_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.TimeField(null=True)),
                ('tuesday', models.TimeField(null=True)),
                ('wednesday', models.TimeField(null=True)),
                ('thursday', models.TimeField(null=True)),
                ('friday', models.TimeField(null=True)),
                ('saturday', models.TimeField(null=True)),
                ('sunday', models.TimeField(null=True)),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Supervisor')),
            ],
        ),
    ]
