# Generated by Django 2.1.5 on 2019-02-04 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190204_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='supervisee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Student'),
        ),
    ]
