# Generated by Django 2.1.5 on 2019-03-23 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190313_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Group'),
        ),
    ]
