# Generated by Django 2.1.5 on 2019-03-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='abstract_text',
            field=models.CharField(default='This is the default abstract text', max_length=1000),
            preserve_default=False,
        ),
    ]
