# Generated by Django 2.1.5 on 2019-02-28 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190227_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='milestone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Milestone'),
            preserve_default=False,
        ),
    ]
