# Generated by Django 2.1.5 on 2019-02-18 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Schedule'),
            preserve_default=False,
        ),
    ]
