# Generated by Django 2.1.5 on 2019-02-04 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_supervisor_supervisee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisor',
            old_name='supervisee',
            new_name='student',
        ),
    ]
