# Generated by Django 2.1.5 on 2019-03-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190323_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group',
            new_name='semester',
        ),
    ]
