# Generated by Django 2.1.5 on 2019-02-04 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190204_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='project',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='student',
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Supervisor'),
        ),
    ]
