# Generated by Django 2.1.5 on 2019-03-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comment_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sender',
            field=models.BooleanField(default=0),
        ),
    ]
