# Generated by Django 2.1.5 on 2019-03-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comment_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sent_date',
            field=models.DateField(auto_now=True),
        ),
    ]
