# Generated by Django 2.1.5 on 2019-03-06 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_completedmilestones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='status',
        ),
        migrations.AlterField(
            model_name='completedmilestones',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Student'),
        ),
    ]
