# Generated by Django 2.1.5 on 2019-03-06 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190306_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedmilestones',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project'),
        ),
    ]
