# Generated by Django 2.1.5 on 2019-03-31 20:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sent_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2019, 3, 31, 20, 55, 5, 36102, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_time',
            field=models.TimeField(auto_now_add=True, default=datetime.datetime(2019, 3, 31, 20, 55, 17, 62770, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='document',
            field=models.FileField(null=True, upload_to='notifications/'),
        ),
    ]
