# Generated by Django 2.1.5 on 2019-02-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190204_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_supervisor',
            field=models.BooleanField(default=True, verbose_name='supervisor_status'),
        ),
    ]
