# Generated by Django 2.1.5 on 2019-03-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_comment_sent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='required_document',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
