# Generated by Django 2.1.5 on 2019-03-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190306_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('NS', 'Not Started'), ('ON', 'Ongoing'), ('FN', 'Finished')], default='NS', max_length=2),
        ),
    ]
