# Generated by Django 2.1.5 on 2019-03-06 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_milestone_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='status',
        ),
    ]
