# Generated by Django 2.1.5 on 2019-02-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190204_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='reg_number',
            field=models.CharField(default='EB1/21493/15', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
