# Generated by Django 2.1.5 on 2019-03-07 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_milestone_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pastproject',
            old_name='past_project',
            new_name='project',
        ),
    ]
