# Generated by Django 2.1.5 on 2019-02-07 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190205_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('approve', models.BooleanField(default=False)),
                ('reject', models.BooleanField(default=False)),
                ('sent_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Student')),
                ('supervisor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='Available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=1)),
            ],
        ),
    ]
