# Generated by Django 2.1.5 on 2019-04-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190401_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
