# Generated by Django 2.1.5 on 2019-03-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190307_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='approved',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Applied', 'Applied'), ('Rejected', 'Rejected')], default='Applied', max_length=10),
        ),
    ]
