# Generated by Django 2.1.5 on 2019-02-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_milestone_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reg_number',
            field=models.CharField(max_length=30),
        ),
    ]
