# Generated by Django 2.1.5 on 2019-02-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190212_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reg_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
