# Generated by Django 2.1.5 on 2019-02-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_student_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='approve',
            new_name='approved',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='reject',
        ),
    ]
