# Generated by Django 2.1.5 on 2019-02-12 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190212_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Student'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='supervisor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Supervisor'),
        ),
    ]
