# Generated by Django 2.1.5 on 2019-02-12 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20190212_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availabledays',
            old_name='days',
            new_name='day',
        ),
    ]
