# Generated by Django 2.1.5 on 2019-02-12 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20190213_0201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvailableDays',
        ),
    ]
