# Generated by Django 2.1.5 on 2019-02-12 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_availabledays'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvailableDays',
        ),
    ]
