# Generated by Django 2.1.5 on 2019-02-12 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_availableday'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvailableDay',
            new_name='AvailableDays',
        ),
    ]
