# Generated by Django 2.1.5 on 2019-02-12 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20190213_0205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvailableDays',
            new_name='AvailableDay',
        ),
    ]
